reference: "/icgc/dkfzlsdf/dmg/otp/production/processing/reference_genomes/bwa06_1KGRef_PhiX/hs37d5_PhiX.fa"

bam_samples:
  - "/icgc/dkfzlsdf/analysis/B060/share/B060_Stuttgart_case/bam_files/WGS/blood/blood_XI046_ST_LFS_1_merged.mdup.bam"