samples: "/icgc/dkfzlsdf/analysis/B060/share/B060_Stuttgart_case/bam_files/WGS/blood/blood_XI046_ST_LFS_1_merged.mdup.bam"

reference: "/icgc/dkfzlsdf/analysis/B260/resource/human/hg19/hg19_no_chr.fa"

outdir: "/icgc/dkfzlsdf/analysis/B260/projects/chromothripsis_medulloblastoma/wgs/gatk_haplotypecaller_calls"